feat: range header support
nftstorage/nftstorage.link pull request #141
Opened 2022-06-03 16:40 UTC by vasco-santos

This PR adds range header support to both content requested from Cache API and from perma cache.

Needs:
- [ ] https://github.com/nftstorage/nftstorage.link/pull/136
- [ ] https://github.com/nftstorage/nftstorage.link/pull/140

Closes #77

2022-06-16 15:20 UTC, alanshaw requested changes

2022-06-16 15:20 UTC, alanshaw commented on packages/api/src/perma-cache/get.js
> +    return new Response(r2Object.body, {
Needs `Content-Range` header e.g. https://github.com/nftstorage/dagcargo-bucket/blob/899070ab67ed2fd39cd1c2f02aad299a179af7e9/src/worker.js#L58

Needs `Content-Length` header e.g. https://github.com/nftstorage/dagcargo-bucket/blob/899070ab67ed2fd39cd1c2f02aad299a179af7e9/src/worker.js#L59

2022-06-16 15:20 UTC, alanshaw commented on packages/api/src/perma-cache/get.js
> +      'Not supported to skip specifying the beginning/ending byte at this time'
Can maybe use this: https://github.com/nftstorage/dagcargo-bucket/blob/main/src/r2.js

2022-06-30 14:37 UTC, vasco-santos commented on packages/edge-gateway/src/gateway.js
> +        cache.match(request.url), // Request URL from cache API - To be deprecated
we need to have this for sometime until cache content is migrated. Let's say 24H?

2022-07-25 08:43 UTC, merged