fix: gateway use cf dns to prevent rate limit instead of durable object
nftstorage/nftstorage.link pull request #36
Opened 2022-04-18 13:43 UTC by vasco-santos

2022-04-19 08:00 UTC, vasco-santos commented
Note: there is currently an error "CNAME cross-user banned". This error happens when we attempt to CNAME to a Cloudflare proxied site. We will need to talk with Pinata to have our domain whitelisted

2022-04-25 08:56 UTC, vasco-santos commented
> Note: there is currently an error "CNAME cross-user banned". This error happens when we attempt to CNAME to a Cloudflare proxied site. We will need to talk with Pinata to have our domain whitelisted

This was arranged with Pinata team and we are now live 🎉  https://pinata.nftstorage.link/ipfs/bafybeiegsdpbk5bs73mtsj2cduyaq3hddra5c33t6vw2vcctxhhxmsd46u

2022-04-25 09:15 UTC, olizilla requested changes

2022-04-25 09:15 UTC, olizilla commented on packages/edge-gateway/wrangler.toml
> +tag = "v5" # Should be unique for each entry
Should be unique for each entry!
```suggestion
tag = "v6" # Should be unique for each entry
```

2022-04-25 10:22 UTC, alanshaw approved these changes
LGTM

2022-04-25 10:23 UTC, olizilla approved these changes

2022-04-25 10:40 UTC, merged